# Generated by Django 5.1.4 on 2026-09-12 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_student_next_class_arm_classbandingconfig_and_more'),
        ('configuration', '0005_classarm_capacity'),
        ('finance', '0006_nonacademicstaffpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('staff_type', models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('exam_officer', 'Exam Officer'), ('accountant', 'Accountant'), ('hr', 'HR'), ('non_academic', 'Non-Academic Staff')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, default='', max_length=20)),
                ('qualification', models.CharField(blank=True, default='', max_length=150)),
                ('is_form_teacher', models.BooleanField(default=False)),
                ('non_academic_role_title', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_payout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_staff_application', to='finance.nonacademicstaffpayout')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_staff_application', to=settings.AUTH_USER_MODEL)),
                ('form_teacher_class_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.classarm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffApplicationSubjectClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_claims', to='staff_onboarding.staffapplication')),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='configuration.classarm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.subject')),
            ],
            options={
                'ordering': ['class_arm__school_class__level_order', 'class_arm__name', 'subject__name'],
                'abstract': False,
            },
        ),
    ]
