# Generated by Django 5.1.4 on 2026-08-22 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('group', models.CharField(max_length=50)),
                ('is_secret', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['group', 'key'],
                'abstract': False,
            },
        ),
    ]
