# Generated by Django 5.1.4 on 2026-08-26 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('key', 'year')},
            },
        ),
    ]
