# Generated by Django 5.1.4 on 2026-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(default='', editable=False, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='', editable=False, max_length=30, unique=True),
        ),
    ]
