# Generated by Django 5.1.4 on 2026-08-27 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_expense_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purpose',
            field=models.CharField(blank=True, choices=[('acceptance_fee', 'Acceptance Fee'), ('first_school_fee', 'First School Fee')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), ('reference__isnull', False)), fields=('reference',), name='finance_payment_reference_uniq'),
        ),
    ]
