# Generated by Django 5.1.4 on 2026-09-11 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_scholarship_payment_is_reconciled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAcademicStaffPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=50)),
                ('beneficiary_code', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(blank=True, max_length=20)),
                ('sort_code', models.CharField(blank=True, max_length=20)),
                ('is_cashcard', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency_code', models.CharField(default='NGN', max_length=10)),
                ('pay_amount', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_academic_payouts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'abstract': False,
            },
        ),
    ]
