# Generated by Django 5.1.4 on 2026-09-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_feecategory_restriction_type'),
        ('finance', '0006_nonacademicstaffpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='configuration.feecategory'),
        ),
    ]
