# Generated by Django 5.1.4 on 2026-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresource',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
