# Generated by Django 5.1.4 on 2026-08-27 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student_guardian_user_student_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='ca_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ReportCardRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('class_teacher_remark', models.TextField(blank=True, default='')),
                ('principal_remark', models.TextField(blank=True, default='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_remarks', to='academics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_remarks', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SkillRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.CharField(choices=[('punctuality', 'Punctuality'), ('neatness', 'Neatness'), ('leadership', 'Leadership'), ('honesty', 'Honesty')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=3)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to='academics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('exam', 'student', 'skill')},
            },
        ),
    ]
