# Generated by Django 5.1.4 on 2026-09-10 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_resultsubmission'),
        ('configuration', '0005_classarm_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='next_class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_students', to='configuration.classarm'),
        ),
        migrations.CreateModel(
            name='ClassBandingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('holding_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.classarm')),
                ('school_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banding_config', to='configuration.schoolclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassReallocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Computed (pending release)'), ('released', 'Released (visible, not yet applied)'), ('applied', 'Applied'), ('superseded', 'Superseded by a newer compute')], default='pending', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations_applied', to=settings.AUTH_USER_MODEL)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations_computed', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations_released', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations', to='configuration.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations', to='configuration.academicsession')),
                ('source_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations', to='academics.exam')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations', to='configuration.term')),
            ],
            options={
                'ordering': ['-computed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassReallocationMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mechanism', models.CharField(choices=[('rerank', 'Performance re-rank (swap)'), ('ns_absorption', 'N_S absorption (additive)'), ('initial_banding', 'Initial banding')], max_length=20)),
                ('term_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_delta', models.SmallIntegerField(default=0)),
                ('from_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.classarm')),
                ('reallocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='academics.classreallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocation_moves', to='academics.student')),
                ('to_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.classarm')),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='classreallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'released'])), fields=('school_class', 'session', 'term'), name='academics_one_live_reallocation_per_class_term'),
        ),
        migrations.AlterUniqueTogether(
            name='classreallocationmove',
            unique_together={('reallocation', 'student')},
        ),
    ]
