# Generated by Django 5.1.4 on 2026-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_next_class_arm_classbandingconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examscore',
            old_name='ca_score',
            new_name='ca1_score',
        ),
        migrations.AddField(
            model_name='examscore',
            name='ca2_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
