# Generated by Django 5.1.4 on 2026-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_split_ca_score_into_ca1_ca2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrating',
            name='skill',
            field=models.CharField(choices=[('honesty', 'Honesty'), ('neatness', 'Neatness'), ('punctuality', 'Punctuality'), ('teamwork', 'Teamwork'), ('games_sport', 'Games/Sport'), ('handwriting', 'Handwriting'), ('interest_in_arts', 'Interest in Arts'), ('music', 'Music')], max_length=20),
        ),
    ]
