# Generated by Django 5.1.4 on 2026-08-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='favicon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
