# Generated by Django 5.1.4 on 2026-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_schoolprofile_city_schoolprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
