# Generated by Django 5.1.4 on 2026-08-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_feecategory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='favicon',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
