# Generated by Django 5.1.4 on 2026-09-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_schoolprofile_favicon_alter_schoolprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classarm',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
