# Generated by Django 5.1.4 on 2026-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_classarm_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_signature',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
