# Generated by Django 5.1.4 on 2026-09-13 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_schoolprofile_principal_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.CharField(choices=[('login_slider', 'Login Page Slider'), ('hero', 'Landing Hero'), ('about_1', 'About Image 1'), ('about_2', 'About Image 2'), ('card', 'Feature Card'), ('gallery_1', 'Gallery 1'), ('gallery_2', 'Gallery 2'), ('gallery_3', 'Gallery 3'), ('album', 'School Album')], max_length=20)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['placement', 'order'],
                'abstract': False,
            },
        ),
    ]
