# Generated by Django 5.1.4 on 2026-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_add_site_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='restriction_type',
            field=models.CharField(blank=True, choices=[('none', 'No restriction'), ('active_student', 'Active Student status (blocks broad academic activity)'), ('library', 'Library (blocks new book loans)'), ('hostel', 'Hostel (blocks hostel room allocation)'), ('transport', 'Transport (blocks school bus/route assignment)'), ('certificate', 'Certificate/Result (blocks report card & result downloads)'), ('activity', 'Activity Participation (blocks joining school activities/events)')], default='none', max_length=20),
        ),
    ]
