# Generated by Django 5.1.4 on 2026-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='entity',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('application', 'Admission Application')], max_length=20),
        ),
    ]
