# Generated by Django 5.1.4 on 2026-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0002_alter_customfield_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='entity',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('parent', 'Parent'), ('application', 'Admission Application')], max_length=20),
        ),
    ]
