# Generated by Django 5.1.4 on 2026-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0003_customfield_is_sensitive_alter_customfield_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Paragraph'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('checkbox', 'Yes/No'), ('attachment', 'Attachment')], default='text', max_length=20),
        ),
    ]
