# Generated by Django 5.1.4 on 2026-09-14 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0004_add_attachment_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('parent', 'Parent'), ('application', 'Admission Application')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['entity', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='custom_fields.customfieldgroup'),
        ),
    ]
