# Generated by Django 5.1.4 on 2026-09-12 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_application_full_name_and_more'),
        ('custom_fields', '0003_customfield_is_sensitive_alter_customfield_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='admissions.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_fields.customfield')),
            ],
            options={
                'ordering': ['field__order', 'field__label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('application', 'field'), name='unique_active_application_custom_field')],
            },
        ),
    ]
